# This is a basic workflow that is manually triggered

name: APO Decisions & FCA Filings Scraper

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Run every 5 minutes

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ 4 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup R with version ${{ matrix.R }}
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - name: Run scrapers
        run: Rscript -e 'print("hello")'

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
