# This is a basic workflow that is manually triggered

name: Statistics

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *' # Run every 20 minutes

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ 4 ]
    steps:
      - uses: actions/checkout@v2
        name: Setup R with version ${{ matrix.R }}
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - name: Install packages
        run: |-
          install.packages('dplyr')
          install.packages('lubridate')
          install.packages('jsonlite')
          install.packages('naniar')
          install.packages('curl')
          
        shell: Rscript {0}
        
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      
      - name: Run R script
        run: |-
          source("Statistics/APO.R")
        shell: Rscript {0}

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
